feat: add deploy check in workflow
kubeclipper/kubeclipper pull request #333
Opened 2022-11-03 07:51 UTC by cmycoups

2022-11-03 08:03 UTC, wu-wenxiang requested changes

2022-11-03 08:03 UTC, wu-wenxiang commented on .github/workflows/aio.yaml
> +          sudo systemctl start kc-agent
合并一下，一起停掉，替换好，再一起开，这样干净，不会有残留数据，比如历史的 agent 数据上报到新的 server 

```yaml
- name: update kc assembly
  run: |
    sudo cp ./dist/kcctl /usr/local/bin/
    sudo systemctl stop kc-agent
    sudo systemctl stop kc-server
    sudo cp ./dist/kubeclipper-agent /usr/local/bin/
    sudo cp ./dist/kubeclipper-server /usr/local/bin/
    sudo systemctl start kc-agent
    sudo systemctl start kc-server
```

2022-11-03 08:03 UTC, wu-wenxiang commented on .github/workflows/aio.yaml
> +          sudo sleep 20s
不要 sudo，暂时 sleep 20 可以，后续可以想办法优化

2022-11-03 08:28 UTC, x893675 commented
/kind workflow
/area testing

2022-11-03 08:28 UTC, x893675 commented
help review first. /cc @lixd

2022-11-03 08:29 UTC, x893675 commented
/retitle ci: add e2e test workflow

2022-11-03 08:31 UTC, x893675 commented
/cc @lixd

2022-11-03 08:32 UTC, x893675 commented
/milestone v1.3.1

2022-11-03 13:16 UTC, wu-wenxiang approved these changes

2022-11-03 13:21 UTC, wu-wenxiang commented
/lgtm

2022-11-04 01:55 UTC, x893675 commented
/remove-approve

2022-11-04 01:56 UTC, x893675 commented
/approve cancel

2022-11-04 02:06 UTC, x893675 commented on .github/workflows/aio.yaml
> +name: test
rename file aio to  e2e-aio
rename job name test to e2e-aio-test

2022-11-04 02:06 UTC, x893675 commented on .github/workflows/aio.yaml
> +      - 'master'
pull request

2022-11-04 02:40 UTC, lixd commented on .github/workflows/aio.yaml
> +      - name: Get branch name
uncessary step

2022-11-04 03:09 UTC, wu-wenxiang commented
/lgtm

2022-11-04 03:10 UTC, merged

2022-11-04 05:35 UTC, x893675 commented
/revert